# Generated by Django 6.1 on 2026-08-09 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/'),
        ),
        migrations.CreateModel(
            name='EvaluatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_assignments', to='core.playerprofile')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('target', 'voter')},
            },
        ),
    ]
