# Generated by Django 6.1 on 2026-08-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_playerprofile_photo_url_playerprofile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='base_average',
        ),
        migrations.AddField(
            model_name='match',
            name='totw_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='growth_carry',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
