# Generated by Django 6.1 on 2026-08-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_playerprofile_base_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='assists',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='assist_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='goal_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
