# Generated by Django 6.1 on 2026-08-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_matchplayer_assists_matchplayer_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.playerprofile')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('player', 'code')},
            },
        ),
    ]
