# Generated by Django 6.1 on 2026-08-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playerbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='team',
            field=models.CharField(blank=True, choices=[('A', 'Equipo A'), ('B', 'Equipo B')], max_length=1, null=True),
        ),
    ]
