# Generated by Django 6.1 on 2026-08-14 18:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_match_finished_at_match_totw_generated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='performance_review_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='performance_review_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchPerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='core.match')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='MatchPerformanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('ritmo', 'ritmo'), ('regate', 'regate'), ('defensa', 'defensa'), ('fisico', 'fisico')], max_length=10)),
                ('delta', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_votes', to='core.match')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_votes_received', to='core.playerprofile')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'voter', 'target')},
            },
        ),
    ]
