# Generated by Django 6.1 on 2026-08-14 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_match_performance_review_applied_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchperformancevote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='matchperformancevote',
            name='attribute',
            field=models.CharField(choices=[('ritmo', 'ritmo'), ('tiro', 'tiro'), ('pase', 'pase'), ('regate', 'regate'), ('defensa', 'defensa'), ('fisico', 'fisico')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='matchperformancevote',
            unique_together={('match', 'voter', 'target', 'attribute')},
        ),
    ]
