# Generated by Django 6.1 on 2026-08-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_matchperformancevote_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='performance_review_applied',
        ),
        migrations.RemoveField(
            model_name='match',
            name='performance_review_applied_at',
        ),
        migrations.CreateModel(
            name='MatchPerformanceApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('ritmo', 'ritmo'), ('tiro', 'tiro'), ('pase', 'pase'), ('regate', 'regate'), ('defensa', 'defensa'), ('fisico', 'fisico')], max_length=10)),
                ('applied_value', models.SmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_applied', to='core.match')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_applied', to='core.playerprofile')),
            ],
            options={
                'unique_together': {('match', 'target', 'attribute')},
            },
        ),
    ]
